## Exercises

Answer the questions or complete the tasks outlined in bold below, use the specific method described if applicable.

** What is 7 to the power of 4?**

In [ ]:
print(pow(7,4))


2401


** Split this string:**

    s = "Hi there Sam!"
    
**into a list. **

In [ ]:
s = "Hi there Sam!"
print(s.split())

['Hi', 'there', 'Sam!']


In [ ]:
s="Hi there dad!"
print(s.split())

['Hi', 'there', 'dad!']


** Given the variables:**

    planet = "Earth"
    diameter = 12742

** Use .format() to print the following string: **

    The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometers".format(planet,diameter) )

The diameter of Earth is 12742 kilometers


In [ ]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

The diameter of Earth is 12742 kilometers.


** Given this nested list, use indexing to grab the word "hello" **

In [ ]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

In [ ]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

print(lst[3][1][2])

['hello']


** Given this nest dictionary grab the word "hello". Be prepared, this will be annoying/tricky **

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

** What is the main difference between a tuple and a list? **

In [ ]:
List is mutable and surrounded with [] 
Tuple is immutable and surrounded with ()

SyntaxError: ignored

** Create a function that grabs the email website domain from a string in the form: **

    user@domain.com
    
**So for example, passing "user@domain.com" would return: domain.com**

In [ ]:
s = "user@domain.com"

def Domain(s):
    a = ""
    found = False
    for i in s:
        if(found):
            a = a+ i
            
        if(i == "@"):
            
            found = True
            
    return a

print(Domain(s))

domain.com


'domain.com'

** Create a basic function that returns True if the word 'dog' is contained in the input string. Don't worry about edge cases like a punctuation being attached to the word dog, but do account for capitalization. **

In [ ]:
def isWordPresent(sentence, word):
    s = sentence.split(" ")
 
    for i in s:
        if (i == word):
            return True
    return False
 
s = "Dog is my favourite pet animal"
word = "Dog"
 
if (isWordPresent(s, word)):
    print("True")
else:
    print("False")
 

True


True

** Create a function that counts the number of times the word "dog" occurs in a string. Again ignore edge cases. **

In [ ]:
def countword(string , search):
    c= 0
    for i in range(len(string)):
        if(string[i:i+len(search)] == search):
            c = c+ 1
          
    return c
print(countword("dog is loved by everyone.A dog can be trained. Dog is a pet animal" , "dog"))

2


In [ ]:
def countword(string , search):
    c= 0
    for i in range(len(string)):
        if(string[i:i+len(search)] == search):
            c = c+ 1
          
    return c
print(countword("dog is loved by everyone.A dog can be trained. Dog is a pet animal" , "dog"))

2


### Problem
**You are driving a little too fast, and a police officer stops you. Write a function
  to return one of 3 possible results: "No ticket", "Small ticket", or "Big Ticket". 
  If your speed is 60 or less, the result is "No Ticket". If speed is between 61 
  and 80 inclusive, the result is "Small Ticket". If speed is 81 or more, the result is "Big    Ticket". Unless it is your birthday (encoded as a boolean value in the parameters of the function) -- on your birthday, your speed can be 5 higher in all 
  cases. **

In [ ]:
def caught_speeding(speed, is_birthday):
    
    if is_birthday:
        speeding = speed - 5
    else:
        speeding = speed
    
    if speeding > 80:
        return 'Big Ticket'
    elif speeding > 60:
        return 'Small Ticket'
    else:
        return 'No Ticket'

Big Ticket
Small Ticket

In [ ]:
def caught_speeding(speed, is_birthday):
    
    if is_birthday:
        speeding = speed - 5
    else:
        speeding = speed
    
    if speeding > 80:
        return 'Big Ticket'
    elif speeding > 60:
        return 'Small Ticket'
    else:
        return 'No Ticket'
print(caught_speeding(95,True))

Big Ticket


In [ ]:
def caught_speeding(speed, is_birthday):
    
    if is_birthday:
        speeding = speed - 5
    else:
        speeding = speed
    
    if speeding > 80:
        return 'Big Ticket'
    elif speeding > 60:
        return 'Small Ticket'
    else:
        return 'No Ticket'
print(caught_speeding(75,False))


Small Ticket


Create an employee list with basic salary values(at least 5 values for 5 employees)  and using a for loop retreive each employee salary and calculate total salary expenditure. 

In [ ]:
employees = ["ram", "shyam", "sindhu", "gagan", "rahul"]    
salary={}
for emp in employees:
       amount=int(input(f'Enter salary for {emp}: '))
       salary[emp]=amount
print('Total salary ',sum(salary.values()))

Enter salary for ram: 3000
Enter salary for shyam: 7000
Enter salary for sindhu: 9000
Enter salary for gagan: 3000
Enter salary for rahul: 10000
Total salary  32000

Create two dictionaries in Python:

First one to contain fields as Empid,  Empname,  Basicpay

Second dictionary to contain fields as DeptName,  DeptId.

Combine both dictionaries. 

In [ ]:
x = {'Empid': 199, 'Empname': "ram","Basicpay":3000}
y = {'DeptName': "finance", 'Deptid': 180}

def merge_two_dicts(x, y):
    z = x.copy() 
    z.update(y)    
    return z
z = merge_two_dicts(x, y)
print(z)


{'Empid': 199, 'Empname': 'ram', 'Basicpay': 3000, 'DeptName': 'finance', 'Deptid': 180}


{'Empid': 199, 'Empname': 'ram', 'Basicpay': 3000, 'DeptName': 'finance', 'Deptid': 180}